### ISSUE TITLE
Autoscroll uses wrong time

### ISSUE THREAD

**Issue by markholster** [jecstarinnovations/etm#37]
When you execute a search with end date 'now', the scroll will not take the first execution timestamp into account. Every scroll starts at the current time.

**Comment by jecstarinnovations** [comment]
The search button is triggering a search with events not later handled that that exact moment. On high stress systems Elasticsearch takes some time to flush those events. That means that events that are handled before the time the search button is pressed will be visible to queries after the button is pressed. Hence they become visible after the first scroll action.

There's no real solution for this, besides not taking the exact time the search button is pressed as the upper limit of events to be found. So in order to prevent this issue the upper limit of events to be found will be the time the search button is pressed minus 5000 milliseconds.
